services:
  app:
    build:
      context: .
    environment:
      PORT: 5005
    depends_on: 
      db:
        condition: service_started 
    ports:
      - 5005:5005
    networks:
      - be
  db: 
    image: postgres:17.5-alpine3.21
    environment:
      POSTGRES_DB: book-store
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - be

networks:
  be:
volumes:
  data:
