services:
  app:
    build:
      context: .
    environment:
      PORT: ${PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on: 
      db:
        condition: service_started 
    ports:
      - ${PORT}:${PORT}
    networks:
      - be
  db: 
    image: postgres:17.5-alpine3.21
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - be

networks:
  be:
volumes:
  data:
