@admin_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoxLCJyb2xlIjoiQWRtaW4ifQ.vK_NyezLxOOMet7k7Z9Tjts8E1VAnZL_IB1ZaaHoeMY
@guest_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoyLCJyb2xlIjoiR3Vlc3QifQ.lkqEm-nzE-9n9GHPHT4WlOBLwvWempGa6M4hLUmlo_s
@host = localhost
@port = 5005


### Delete a book success

DELETE http://{{host}}:{{port}}/books/9780743273565 HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

### Delete a book failed (Not found)

DELETE http://{{host}}:{{port}}/books/9780743273566 HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

### Delete a book failed (Invalid format)

DELETE http://{{host}}:{{port}}/books/978074327356 HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

### Delete a category success

DELETE http://{{host}}:{{port}}/categories/Detective HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json
