@base_url = localhost:5005
@host = localhost
@port = 5005


### Ping

GET http://{{base_url}}/ HTTP/1.1

### Not found

GET http://{{base_url}}/api HTTP/1.1

### Get all books

GET http://{{base_url}}/books HTTP/1.1

### Get a book by ISBN

GET http://{{base_url}}/books/9780743273565 HTTP/1.1

### Get books by category 

GET http://{{base_url}}/books?category=Romantic HTTP/1.1

### Get categories by name

GET http://{{base_url}}/categories/Detective HTTP/1.1

### Get all categories 

GET http://{{base_url}}/categories HTTP/1.1
