@admin_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoxLCJyb2xlIjoiQWRtaW4ifQ.vK_NyezLxOOMet7k7Z9Tjts8E1VAnZL_IB1ZaaHoeMY
@guest_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoyLCJyb2xlIjoiR3Vlc3QifQ.lkqEm-nzE-9n9GHPHT4WlOBLwvWempGa6M4hLUmlo_s
@host = localhost
@port = 5005


### Register failed with empty body

POST http://{{host}}:{{port}}/register HTTP/1.0
Content-Type: application/json

### Register failed with missing fields 

POST http://{{host}}:{{port}}/register HTTP/1.0
Content-Type: application/json

{
  "email": "hehe"
}

### Register success

POST http://{{host}}:{{port}}/register HTTP/1.0
Content-Type: application/json

{
  "email": "hehe",
  "password": "hehe",
  "first_name": "Hung",
  "last_name": "Pham",
  "dob": "2005-06-17"
}

### Login success

POST http://{{host}}:{{port}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "hehe",
  "password": "hehe"
}

### Login failed with wrong passwrod

POST http://{{host}}:{{port}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "hehe1",
  "password": "hehe"
}

### Login failed with empty data

POST http://{{host}}:{{port}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "hehe",
  "password": ""
}

### Verify success

POST http://{{host}}:{{port}}/verify HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoyLCJyb2xlIjoiR3Vlc3QifQ.lkqEm-nzE-9n9GHPHT4WlOBLwvWempGa6M4hLUmlo_s
Content-Type: application/json

### Verify failed

POST http://{{host}}:{{port}}/verify HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjozfQ.uVXulBATR1UapKWt-paPlhLN1y1Q9yW587swgPltkc
Content-Type: application/json

### Add book success

POST http://{{host}}:{{port}}/books HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "description": "A classic novel about the American Dream",
  "isbn": "9780743273565",
  "author": "F. Scott Fitzgerald",
  "category": "Romantic"
}

### Add one more contains 'Great' keyword

POST http://{{host}}:{{port}}/books HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "title": "Great Expectations",
  "description": "A coming-of-age story of an orphan named Pip",
  "isbn": "9780141439563",
  "author": "Charles Dickens",
  "category": "Detective"
}

### Add book failed with contains hyphens

POST http://{{host}}:{{port}}/books HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "description": "A classic novel about the American Dream",
  "isbn": "978-0-7432-7356-5",
  "author": "F. Scott Fitzgerald",
  "category": "Hehe"
}

### Add category success

POST http://{{host}}:{{port}}/categories HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "name": "Detective",
  "description": "Like Sherlock Holmes"
}

### Add one more category success

POST http://{{host}}:{{port}}/categories HTTP/1.1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "name": "Detector",
  "description": "Like Sherlock Holmes"
}
